In [103]:
#########################
# Numpy
#########################
# documentación
# https://numpy.org/doc/1.19/reference/index.html

# import
from numpy import abs
import numpy as np
print(np.abs(-5), abs(-10))

5 10


In [83]:
# listas y arreglos de numpy
lista = [56,  69,  88,  67, 113,  96,  73,  83, 172, 173]
np_array = np.array(lista)
np_array

array([ 56,  69,  88,  67, 113,  96,  73,  83, 172, 173])

In [105]:
np_array_float = np.array(lista, dtype='float')
np_array_float, type(np_array)

(array([ 56.,  69.,  88.,  67., 113.,  96.,  73.,  83., 172., 173.]),
 numpy.ndarray)

In [85]:
lista[0], np_array[0]

(56, 56)

In [86]:
type(lista[0]), type(np_array[0]), type(np_array_float[0])
np_array_float = np.array(lista, dtype=np.float32)
np_array_float, type(np_array_float[0])

(array([ 56.,  69.,  88.,  67., 113.,  96.,  73.,  83., 172., 173.],
       dtype=float32),
 numpy.float32)

In [91]:
# suma, producto, mínimo, máximo en listas y numpy arrays
lista = [56,  69,  88,  67, 113,  96,  73,  83, 172, 173]
np_array = np.array(lista)
np_array

array([ 56,  69,  88,  67, 113,  96,  73,  83, 172, 173])

In [92]:
sum(lista), sum(np_array)

(990, 990)

In [93]:
np.sum(np_array), np.sum(lista)

(990, 990)

In [94]:
np.prod(np_array)

-320102400

In [95]:
min(lista), np.min(np_array)

(56, 56)

In [90]:
max(lista), np.max(np_array)

(173, 173)

In [106]:
# operaciones vectorizadas
lista = [56,  69,  88,  67, 113]
np_array = np.array(lista)
np_array


array([ 56,  69,  88,  67, 113])

In [97]:
print(3 * lista)

[56, 69, 88, 67, 113, 96, 73, 83, 172, 173, 56, 69, 88, 67, 113, 96, 73, 83, 172, 173, 56, 69, 88, 67, 113, 96, 73, 83, 172, 173]


In [98]:
lista_x3 = [3*n for n in lista]
print(lista_x3)

[168, 207, 264, 201, 339, 288, 219, 249, 516, 519]


In [107]:
3 * np_array, 5 + np_array

(array([168, 207, 264, 201, 339]), array([ 61,  74,  93,  72, 118]))

In [109]:
[1/n for n in lista], 1 / np_array

([0.017857142857142856,
  0.014492753623188406,
  0.011363636363636364,
  0.014925373134328358,
  0.008849557522123894],
 array([0.01785714, 0.01449275, 0.01136364, 0.01492537, 0.00884956]))

In [111]:
# operaciones avanzadas
# Función sigmoidal para cada elemento
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


lista = [0.5,  0.2,  0.1, 0.3, 0.4]
np_array = np.array(lista)
np_array

array([0.5, 0.2, 0.1, 0.3, 0.4])

In [112]:
np.exp(np_array)

array([1.64872127, 1.22140276, 1.10517092, 1.34985881, 1.4918247 ])

In [113]:
-np_array

array([-0.5, -0.2, -0.1, -0.3, -0.4])

In [114]:
np_array_exp = 1 / (1 + np.exp(-np_array))
np_array_exp

array([0.62245933, 0.549834  , 0.52497919, 0.57444252, 0.59868766])

In [115]:
# suma y multiplicación de listas y numpy arrays
a = [2, 3, 4, 5, 6]
b = [10, 20, 30, 40, 50]
a_np = np.array([2, 3, 4, 5, 6])
b_np = np.array([10, 20, 30, 40, 50])
a_np, b_np

(array([2, 3, 4, 5, 6]), array([10, 20, 30, 40, 50]))

In [32]:
a+b

array([ 2,  3,  4,  5,  6, 10, 20, 30, 40, 50])

In [34]:
a_np + b_np

array([12, 23, 34, 45, 56])

In [33]:
np.concatenate([a_np, b_np])

array([ 2,  3,  4,  5,  6, 10, 20, 30, 40, 50])

In [118]:
# comparación de tiempos de ejecución
lista = list(range(100000000))
numpy_array = np.array(lista)


def suma(lista):
    suma = 0
    for n in lista:
        suma = suma + n
    return suma

# %timeit suma(lista)
# %timeit sum(lista)
# %timeit np.sum(numpy_array)

In [52]:
# atributos, métodos y funciones
np_array = np.array(range(20))
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
np_array.shape

(20,)

In [48]:
np.sum(np_array)

190

In [49]:
np_array.sum()

190

In [53]:
# indexado de elementos
np_array = np.array(range(20)).reshape(4,5)
np_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
np_array[2,3]

13

In [55]:
np_array > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [56]:
np_array % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [57]:
np_array[np_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
np_array[np_array > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
# slicing de numpy arrays
lista = [10, 20, 30, 40 ,50, 60, 70, 80, 90, 100]
lista[2:8:2]

[30, 50, 70]

In [65]:
np_array = np.array(range(100)).reshape(10,10)
np_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
np_array[2:5,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
np_array[2:5,2:4]

array([[22, 23],
       [32, 33],
       [42, 43]])

In [68]:
np_array[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [69]:
# axis
np_array_multi = np.random.randint(10, 50, 20).reshape((4,5))
np_array_multi

array([[39, 49, 19, 36, 18],
       [33, 33, 43, 18, 37],
       [39, 11, 49, 31, 24],
       [49, 20, 41, 40, 40]])

In [70]:
np.sum(np_array_multi)

669

In [71]:
np.sum(np_array_multi, axis = 0)

array([160, 113, 152, 125, 119])

In [72]:
np.sum(np_array_multi, axis = 1)

array([161, 164, 154, 190])

In [73]:
np.sort(np_array_multi, axis = 0)

array([[33, 11, 19, 18, 18],
       [39, 20, 41, 31, 24],
       [39, 33, 43, 36, 37],
       [49, 49, 49, 40, 40]])

In [74]:
np.sort(np_array_multi, axis=1)

array([[18, 19, 36, 39, 49],
       [18, 33, 33, 37, 43],
       [11, 24, 31, 39, 49],
       [20, 40, 40, 41, 49]])

In [75]:
np.sort(np_array_multi)

array([[18, 19, 36, 39, 49],
       [18, 33, 33, 37, 43],
       [11, 24, 31, 39, 49],
       [20, 40, 40, 41, 49]])